name: build

on:
  push:
    branches:
      - trigger
  workflow_dispatch:

jobs:
  abuse:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize space
        uses: easimon/maximize-build-space@master
        with:
          build-mount-path: '/home/runner'
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup cloudflared ssh
        uses: NORALDM/action-sshd-cloudflared@master
        env:
          GIST: ${{ secrets.GIST }}
          TOKEN: ${{ secrets.TOKEN }}
          PAT: ${{ secrets.PAT }}
          ARCH: amd64
